version: '3'
services:
  web:
    image: nginx
    container_name: nginx2
    ports:
      - "8081:80"
    volumes:
      - "/home/oriol/docker/compose/html:/usr/share/nginx/html"  # mapping /home/oriol/docker/compose/html in /usr/share/nginx/html
    