version: '3'
services:
  web1:
    image: nginx
    container_name: web1
    ports:
      - "8083:80"   
    networks:
      - net-test
  web2:
    image: httpd
    container_name: web2
    ports:
      - "8084:80"
    networks:
      - net-test
networks:
  net-test: