version: '3'
services:
  web:
    image: nginx
    container_name: nginx1
    ports:
      - "8080:80"
    volumes:
      - "vol2:/usr/share/nginx/html"  # mount vol2 in /usr/share/nginx/html    
volumes:
  vol2:  # created vol2