version: "3.1"
services:

#APIRest in nodejs 
   #Optional you can create the node apirest image  (# docker build -t nodeapirest) .
  nodeapirest: 
    #build: . #build: Dockerfile #Optional : "build: ." Uses an image that’s built from the Dockerfile in the current directory.  
    image: nodeapirest
    container_name: "nodeapirest"      
    restart: always
    ports:
      - 3000:3000
    
    environment:
      NODE_ENV: "docker"