FROM mysql

LABEL maintainer="oriol.amat@gmail.com"
LABEL version="1.0"
LABEL description="mysql image test"

#RUN yum -y install httpd php php-cli php-comon openssl mod_ssl

#WORKDIR /var/www/html

# Copy a website, with WORKDIR I can use "." to referer it :
#COPY php .   

EXPOSE 3306


#CMD apachectl -DFOREGROUND